news/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from .views import (
    news_list,
    news_detail,
    # press_list,
    # press_detail,
)

urlpatterns = [
    url(r'^$', news_list, name='news_list'),
    url(r'^(?P<id>\d+)/$', news_detail, name='news_detail'),
    url(r'^press/$', news_list, {'mode': 'press'}, name='press_list'),
    url(r'^press/(?P<id>\d+)/$', news_detail, {'mode': 'press'}, name='press_detail'),
]

open_gov/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^news/', include("news.urls", namespace='news')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^search/', views.search),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
from django.db import models
from tinymce.models import HTMLField
from django.core.urlresolvers import reverse
# from open_gov.settings import TINYMCE_PROFILE
from . import settings


# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    # content = HTMLField()
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("news:news_detail", kwargs={"id": self.id})

    class Meta:
        ordering = ["-timestamp", "-updated"]


class PostPress(models.Model):
    title = models.CharField(max_length=255)
    smiTitle = models.CharField(max_length=255)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    # content = HTMLField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("news:press_detail", kwargs={"id": self.id})

news/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Post, PostPress

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render


# Create your views here.


def news_list(request, mode=None):
    if not mode:
        queryset_list = Post.objects.all()  # .order_by("-timestamp")
    else:
        queryset_list = PostPress.objects.all()  # .order_by("-timestamp")

    paginator = Paginator(queryset_list, 2)  # Show 25 contacts per page
    page_request_var = 'page'
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    context = {
        "queryset_list": queryset,
        "page_request_var": page_request_var,
        'range_pagination': range(1, queryset.paginator.num_pages + 1)
    }
    return render(request, 'news_list.html', context)


def news_detail(request, id=None, mode=None):
    if not mode:
        instance = get_object_or_404(Post, id=id)
    else:
        instance = get_object_or_404(PostPress, id=id)
    context = {
        "title": instance.title,
        "instance": instance,
    }
    return render(request, 'news_detail.html', context)

open_gov/views.py
from django.http import HttpResponse
from django.shortcuts import render

from news.models import Post, PostPress


def index(request):
    qs_news = Post.objects.order_by("-timestamp")[:3]
    qs_press = PostPress.objects.order_by("-timestamp")[:3]
    context = {
        "news": qs_news,
        "press": qs_press,
    }
    return render(request, 'index.html', context)


def search(request):
    return render(request, 'search.html')

templates/banners-bottom-slider.html
<div class="row">
    <div class="col-md-12 opengov-carousel">
        <div id="Carousel" class="carousel slide">

            <!--<ol class="carousel-indicators">-->
                <!--<li data-target="#Carousel" data-slide-to="0" class="active"></li>-->
                <!--<li data-target="#Carousel" data-slide-to="1"></li>-->
                <!--<li data-target="#Carousel" data-slide-to="2"></li>-->
            <!--</ol>-->

            <!-- Carousel items -->
            <div class="carousel-inner">

                <div class="item active">
                    <div class="row">
                        <div class="col-md-3"><a href="#" class="thumbnail"><img src="/media/banner_site_gubernator_ko.png"
                                                                                 alt="Image"
                                                                                 style="max-width:100%;"></a></div>
                        <div class="col-md-3"><a href="#" class="thumbnail"><img src="/media/banner_ep.png"
                                                                                 alt="Image"
                                                                                 style="max-width:100%;"></a></div>
                        <div class="col-md-3"><a href="#" class="thumbnail"><img src="/media/banner_vash_kontrol.png"
                                                                                 alt="Image"
                                                                                 style="max-width:100%;"></a></div>
                        <div class="col-md-3"><a href="#" class="thumbnail"><img src="/media/banner_roi.png"
                                                                                 alt="Image"
                                                                                 style="max-width:100%;"></a></div>
                    </div><!--.row-->
                </div><!--.item-->

            </div><!--.carousel-inner-->
            <!--<a data-slide="prev" href="#Carousel" class="left carousel-control">‹</a>-->
            <!--<a data-slide="next" href="#Carousel" class="right carousel-control">›</a>-->
        </div><!--.Carousel-->

    </div>
</div>

templates/banners_left.html
<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">

    <div class="col-xs-6 col-sm-6 col-md-12 col-lg-12 top-buffer">
        <a href="/"><img src="/media/open_gov.png" alt="" class="img-responsive"></a>
    </div>

    <div class="col-md-12 col-lg-12 hidden-xs hidden-sm top-buffer opengov-block-header">
        <span class="opengov-block-span-header">Сервисы</span>
    </div>

    <div class="col-xs-6 col-sm-6 col-md-12 col-lg-12 top-buffer opengov-block">
        <a href="#"><span class="opengov-block-span">Государственные и муниципальные услуги</span></a>
    </div>
    <div class="col-xs-6 col-sm-6 col-md-12 col-lg-12 top-buffer opengov-block">
        <a href="#">
            <span class="opengov-block-span">
                ИНТЕРНЕТ-ПРИЕМНАЯ<br>
                <img src="/media/gerb_kontur.png" alt="" class="img-responsive img-center" height="60px" width="50px">
                Губернатора Калининградской области
            </span>
        </a>
    </div>
    <div class="col-xs-6 col-sm-6 col-md-12 col-lg-12 top-buffer opengov-block">
        <a href="#"><span
                class="opengov-block-span">Трансляция заседаний Правительства области</span></a>
    </div>
    <div class="col-xs-6 col-sm-6 col-md-12 col-lg-12 top-buffer opengov-block">
        <a href="#"><span
                class="opengov-block-span">Материалы заседаний Правительства области</span></a>
    </div>
    <div class="col-xs-6 col-sm-6 col-md-12 col-lg-12 top-buffer opengov-block">
        <a href="#">
            <span class="opengov-block-span"><img src="/media/pa.png" alt="" class="img-responsive img-banner-left"><i>Правовые акты</i> органов государственной власти Калининградской области</span>
        </a>
    </div>
    <div class="col-xs-6 col-sm-6 col-md-12 col-lg-12 top-buffer opengov-block">
        <a href="#">
            <span class="opengov-block-span"><img src="/media/npa.png" alt="" class="img-responsive img-banner-left">Независимая антикоррупционная экспертиза НПА</span>
        </a>
    </div>
    <div class="col-xs-6 col-sm-6 col-md-12 col-lg-12 top-buffer opengov-block">
        <a href="#"><span
                class="opengov-block-span">Публичное обсуждение нормативно-правовых акто</span></a>
    </div>
    <div class="col-xs-6 col-sm-6 col-md-12 col-lg-12 top-buffer opengov-block">
        <a href="#"><span class="opengov-block-span">Открытые данные</span></a>
    </div>
    <div class="col-xs-6 col-sm-6 col-md-12 col-lg-12 top-buffer opengov-block">
        <a href="#"><span class="opengov-block-span">Общественные советы</span></a>
    </div>
</div>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="/media/favicon.ico" type="image/x-icon">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Открытое Правительство Калининградской области</title>
    {% load staticfiles %}
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-carousel.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-search.css' %}" rel="stylesheet">


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

</head>
<body>
{% include "nav.html" %}

<div class="container main">

    <br>

    <div class="row">
        {% include "banners_left.html" %}
        <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
            {% block content %}

            {% endblock content %}
        </div>
    </div>

    {% if request.path == "/" %}
        {% include "banners-bottom-slider.html" %}
    {% endif %}

    <hr>
    {% include 'footer.html' %}

</div>


<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/carousel.js' %}"></script>
<script src="{% static 'js/search.js' %}"></script>
<script src="{% static 'js/popup-share.js' %}"></script>
</body>
</html>

templates/footer.html
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
        <div class="opengov-footer">
            <p>Почтовый адрес: 236007, г. Калининград, ул. Дм. Донского, 1<br>
            Обращения граждан принимаются в интернет-приемной губернатора калининградской области<br>
            &copy; 2016 Правительство Калининградской области<br>
            По вопросам работы сайта обращайтесь по e-mail: <a mailto="site@gov39.ru">site@gov39.ru</a> с пометкой "Сайт Открытого Правительства Калининградской области"</p>
        </div>
    </div>
    <div class="hidden-xs hidden-sm col-md-3 col-lg-3"><img src="/media/open_gov.png" alt=""
                                                          class="img-responsive"></div>
</div>

templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="row bottom-buffer opengov-block-header">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <span class="opengov-block-span-header">Лента событий</span>
    </div>
</div>
{% for post in news %}
<div class="row opengov-post">
    <!-- Link trigger modal -->
    <a href="{{ post.get_absolute_url }}" data-toggle="modal" data-target="#opengovModal" data-remote="false">
        <div class="col-md-5 top-buffer">
            <!--<img src="http://placehold.it/270x180" alt="" class="img-responsive">-->
            <img src="{{ post.image.url }}" alt="" class="img-responsive">
        </div>
        <div class="col-md-7 top-buffer">
            <p><span class="date">{{ post.timestamp|date:"d.m.Y" }}</span></p>
            <h4>{{ post.title }}</h4>
            <p>{{ post.content|removetags:""|safe|slice:":130" }}...</p>
        </div>
    </a>


    <!-- Default bootstrap modal example -->
    <div class="modal fade" id="opengovModal" tabindex="-1" role="dialog" aria-labelledby="opengovModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h3 class="modal-title" id="opengovModalLabel"><span
                            class="date">{{ post.timestamp|date:"d.m.Y" }}</span></h3>
                </div>
                <div class="modal-body">

                </div>

            </div>
        </div>
    </div>

    <script language="JavaScript">
        // Fill modal with content from link href
        $("#opengovModal").on("show.bs.modal", function (e) {
            var link = $(e.relatedTarget);
            $(this).find(".modal-body").load(link.attr("href"));
        });
    </script>
</div>
<hr>
{% endfor %}


<div class="row">
    <p class="text-center"><a href="{% url 'news:news_list' %}"><b><span class="date">ВСЕ СОБЫТИЯ</span></b></a></p>
</div>
<hr>

<div class="row bottom-buffer opengov-block-header">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <span class="opengov-block-span-header">Пресса о нас</span>
    </div>
</div>

{% for post_press in press %}
<div class="row">
    <div class="col-md-12">
        <!-- Link trigger modal -->
        <a href="{{ post_press.get_absolute_url }}" data-toggle="modal" data-target="#opengovModal" data-remote="false">
            <p><span class="date">{{ post_press.timestamp|date:"d.m.Y" }}</span><br>
                <span class="smi-title">{{ post_press.smiTitle }}</span><br>
                {{ post_press.title }}</p>
        </a>


        <!-- Default bootstrap modal example -->
        <div class="modal fade" id="opengovModal" tabindex="-1" role="dialog" aria-labelledby="opengovModalLabel"
             aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h3 class="modal-title" id="opengovModalLabel"><span
                            class="date">{{ post.timestamp|date:"d.m.Y" }}</span></h3>
                    </div>
                    <div class="modal-body">

                    </div>

                </div>
            </div>
        </div>

        <script language="JavaScript">
            // Fill modal with content from link href
            $("#opengovModal").on("show.bs.modal", function (e) {
                var link = $(e.relatedTarget);
                $(this).find(".modal-body").load(link.attr("href"));
            });
        </script>
    </div>
</div>
<hr>
{% endfor %}

<div class="row">
    <p class="text-center"><a href="{% url 'news:press_list' %}"><b><span class="date">ВСЕ МАТЕРИАЛЫ</span></b></a>
    </p>
</div>
<hr>
{% endblock content %}

templates/nav.html
<nav class="navbar navbar-inverse navbar-static-top opengov-navbar navbar-bootsnipp animate">
    <div class="container">
        <div class="row">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#responsive-menu">
                    <span class="sr-only">Открыть навигацию</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <!-- <a href="#" class="navbar-brand">Название</a> -->
            <div class="collapse navbar-collapse" id="responsive-menu">
                <ul class="nav navbar-nav navbar-open ">
                    <li class="[ visible-xs ]">
                        <form action="http://bootsnipp.com/search" method="GET" role="search">
                            <div class="[ input-group ]">
                                <input type="text" class="[ form-control ]" name="q" placeholder="Поиск по сайту">
								<span class="[ input-group-btn ]">
									<button class="[ btn btn-primary ]" type="submit"><span
                                            class="[ glyphicon glyphicon-search ]"></span></button>
									<button class="[ btn btn-danger ]" type="reset"><span
                                            class="[ glyphicon glyphicon-remove ]"></span></button>
								</span>
                            </div>
                        </form>
                    </li>
                    <li class="active"><a href="/"><span class="glyphicon glyphicon-home icon-white" aria-hidden="true"></span></a>
                    </li>
                    <li><a href="#about">Сервисы</a></li>
                    <li><a href="#contact">О проекте</a></li>
                    <li><a href="#contact">Документы</a></li>
                    <li><a href="#contact">Рабочая группа</a></li>
                    <li><a href="#contact">Опросы</a></li>
                    <li><a href="#contact">Обратная связь</a></li>
                    <!--<li><a href="#contact"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></a></li>-->
                    <li class="[ hidden-xs ]"><a href="#toggle-search"><span
                            class="[ glyphicon glyphicon-search ]"></span></a>
                    </li>


                </ul>
                <!--<ul class="nav navbar-nav navbar-right navbar-open-right">-->
                <!--<li class="[ hidden-xs ]"><a href="#toggle-search" class="[ animate ]"><span-->
                <!--class="[ glyphicon glyphicon-search ]"></span></a>-->
                <!--</li>-->
                <!--</ul>-->
            </div>

        </div>
    </div>

    <div class="[ bootsnipp-search animate ]">
        <div class="[ container ]">
            <form action="#" method="GET" role="search">
                <div class="[ input-group ]">
                    <input type="text" class="[ form-control ]" name="q"
                           placeholder="Поиск по сайту">
						<span class="[ input-group-btn ]">
							<button class="[ btn btn-danger ]" type="reset"><span
                                    class="[ glyphicon glyphicon-remove ]"></span></button>
						</span>
                </div>
            </form>
        </div>
    </div>

</nav>

templates/news_detail.html
{#{% extends "base.html" %}#}

{#{% block content %}#}
<div class="row">
    {% if instance.image.url %}
    <div class="col-xs-6 col-sm-6 col-md-7 col-ls-7">
        <img src="{{ instance.image.url }}" alt="" class="img-responsive">
    </div>
    {% endif %}
    <div class="col-xs-12 col-sm-12 col-md-12">
        <h1>{{ instance.title }}</h1>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        {# <h2>{{ title }}</h2>#}
        <p>{{ instance.content|removetags:""|safe }}</p>
        {% if instance.smiTitle %}
        <p><span class="smi-title">{{ instance.smiTitle }}</span></p>
        {% endif %}
    </div>
</div>

<br>
<div class="row">
    <div class="col-md-12">
        <p>
        <p><b><span class="date">Поделиться:</span></b></p>
        <ul class="opengov-share">
            <li><i class="fa fa-share-alt fa-2x" aria-hidden="true"></i></li>
            <li>
                <!--<a href="http://vk.com/share.php?url={{ instance.get_absolute_url }}" class="vk popup">-->
                <a href="http://vk.com/share.php?url={{ request.build_absolute_uri }}" class="vk popup">
                    <i class='fa fa-vk fa-2x' aria-hidden='true' style='color:#45668e'></i>
                </a>
            </li>
            <li>
                <a class="twitter popup" href="http://twitter.com/share">
                    <i class="fa fa-twitter fa-2x" aria-hidden="true" style="color: #55acee"></i>
                </a>
            </li>
            <li>
                <a href="http://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" class="fb popup">
                    <i class="fa fa-facebook fa-2x" aria-hidden="true" style="color: #3b5998"></i>
                </a>
            </li>
            <li>
                <a href="https://plus.google.com/share?url={{ request.build_absolute_uri }}" class="google-plus popup">
                    <i class="fa fa-google-plus fa-2x" aria-hidden="true" style="color: #dc4e41"></i>
                </a>
            </li>
        </ul>
        </p>
    </div>
</div>


{# {% if instance.image.url %}#}
{# <p><a href="{% url 'news:news_list' %}"><span class="date">Вернуться к списку новостей</span></a></p>#}
{# {% else %}#}
{# <p><a href="{% url 'news:press_list' %}"><span class="date">Вернуться к списку материалов</span></a></p>#}
{# {% endif %}#}
{#{% endblock content %}#}

templates/news_list.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h3 class="news-list-header">Лента событий</h3>
        <nav style="float: right">
            <ul class="pagination news-list-pagination">
                {% if queryset_list.has_previous %}
                <li>
                    <a href="?{{ page_request_var }}={{ queryset_list.previous_page_number }}"
                       aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}
                {% for i in range_pagination %}
                <li><a href="?{{ page_request_var }}={{ i }}">{{ i }}</a></li>
                {% endfor %}
                {% if queryset_list.has_next %}
                <li>
                    <a href="?{{ page_request_var }}={{ queryset_list.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>
<div class="row bottom-buffer opengov-block-header">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <span class="opengov-block-span-header opengov-block-span-header-list"></span>
    </div>
</div>


{% for post in queryset_list %}
<div class="row opengov-post">
    <!-- Link trigger modal -->
    <a href="{{ post.get_absolute_url }}" data-toggle="modal" data-target="#opengovModal" data-remote="false">
        {% if post.image.url %}
        <div class="col-md-5 top-buffer"><img src="{{ post.image.url }}" class="img-responsive"></div>
        <div class="col-md-7 top-buffer">
            <p><span class="date">{{ post.timestamp|date:"d.m.Y" }}</span></p>
            <h4>{{ post.title }}</h4>
            <p>{{ post.content|removetags:""|safe|slice:":150" }} ... </p>
        </div>
        {% else %}
        <div class="col-md-12 top-buffer">
            <p><span class="date">{{ post.timestamp|date:"d.m.Y" }}</span></p>
            <h4>{{ post.title }}</h4>
            <p>{{ post.content|removetags:""|safe|slice:":250" }} ...</p>
        </div>
        {% endif %}
    </a>


    <!-- Default bootstrap modal example -->
    <div class="modal fade" id="opengovModal" tabindex="-1" role="dialog" aria-labelledby="opengovModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <!--<h2 class="modal-title" id="opengovModalLabel">{{ post.title }}</h2>-->
                    <h3 class="modal-title" id="opengovModalLabel"><span
                            class="date">{{ post.timestamp|date:"d.m.Y" }}</span></h3>
                </div>
                <div class="modal-body">

                </div>

            </div>
        </div>
    </div>

    <script language="JavaScript">
        // Fill modal with content from link href
        $("#opengovModal").on("show.bs.modal", function (e) {
            var link = $(e.relatedTarget);
            $(this).find(".modal-body").load(link.attr("href"));
        });
    </script>
</div>
<hr>
{% endfor %}


{% endblock content %}